{
    "launchType": "FARGATE",
    "serviceName": testapp,
    "desiredCount": 1,
    "networkConfiguration": {
        "awsvpcConfiguration": {
            "securityGroups": [
                "<your security group e.g sg-1234567890abcdefg"
            ],
            "subnets": [
                "your subnet for availability zone a subnet-1234567890abcdefg",
                "your subnet for availability zone b subnet-1234567890abcdefg",
                "your last subnet for availability zone x subnet-1234567890abcdefg"
            ],
            "assignPublicIp": "ENABLED"
        }
    },
    "deploymentConfiguration": {
        "maximumPercent": 100,
        "minimumHealthyPercent": 0
    }
}
